set guifont=FantasqueSansMono\ 10

set guioptions-=T   " no toolbar
set guioptions-=l   " no scrollbar on the left
set guioptions-=L
set guioptions-=r   " no scrollbar on the right
set guioptions-=R
set guioptions-=m

if filereadable($HOME."/.vim/gvimrc.local")
  source ~/.vim/gvimrc.local
endif
